---
- name: Update Infoblox credential
  hosts: localhost
  gather_facts: false

  vars:
    _infoblox_region: '{{ vnios_aws_region | default(create_vm_aws_region) | default("us-west-2") }}'
    _infoblox_host: '{{ vnios_instance_name | default("apd-infoblox") }}'
    _infoblox_username: '{{ vnios_instance_user | default("admin") }}'

  tasks:
    - name: Query Infoblox instance information
      amazon.aws.ec2_instance_info:
        region: '{{ _infoblox_region }}'
        filters:
          'tag:Name': '{{ _infoblox_host }}'
      register: _instance_info

    - name: Set public DNS name fact from ENI with elastic IP
      ansible.builtin.set_fact:
        _public_dns_name: >-
          {{ ( _instance_info.instances[0].network_interfaces
               | selectattr("association", "defined")
               | first
             ).association.public_dns_name
          }}

    - name: Update Infoblox credential with the new Infoblox FQDN
      ansible.controller.credential:
        name: Infoblox
        state: present
        credential_type: Infoblox
        organization: Ansible Product Demos (APD)
        update_secrets: false
        inputs:
          host: '{{ _public_dns_name }}'
          username: '{{ _infoblox_username }}'
          # work around update_secrets bug
          # https://github.com/ansible/awx/issues/13169
          password: '$encrypted$'

...
# vim: ft=yaml.ansible
