---
- name: Magic vars test
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display inventory_dir and playbook_dir
      ansible.builtin.debug:
        msg:
          - "inventory_dir is: {{ inventory_dir }}"
          - "playbook_dir is: {{ playbook_dir }}"

    - name: Get content of /runner/project
      ansible.builtin.command: >
        ls -l /runner/project
      register: _project_dir

    - name: Get content of /runner/project
      ansible.builtin.debug:
        var: _project_dir

...
