---
- name: Magic vars test
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Display inventory_dir and playbook_dir
      ansible.builtin.debug:
        msg:
          - "inventory_dir is: {{ inventory_dir }}"
          - "playbook_dir is: {{ playbook_dir }}"

    - name: Get content of /runner/project
      ansible.builtin.command: >
        ls -l /runner/project
      register: _project_dir

    - name: Display content of /runner/project
      ansible.builtin.debug:
        var: _project_dir

    - name: Get content of /runner/inventory
      ansible.builtin.command: >
        ls -l /runner/inventory
      register: _inventory_dir

    - name: Display content of /runner/inventory
      ansible.builtin.debug:
        var: _inventory_dir

    - name: Get content of /runner/inventory/hosts
      ansible.builtin.command: >
        cat /runner/inventory/hosts
      register: _hosts_file

    - name: Display content of /runner/inventory/hosts
      ansible.builtin.debug:
        var: _hosts_file

...
