---
- name: Check that a web URL is available
  hosts: localhost

  sources:
    - name: Check web URL
      ansible.eda.url_check:
        urls:
          - '{{ web_server_url | default("https://www.redhat.com/") }}'
        delay: 60
        verify_ssl: '{{ web_server_verify_ssl | default(true) }}'

  rules:
    - name: Restart web server
      condition: event.url_check.status == "down"
      actions:
        - debug:
        - run_job_template:
            name: LINUX | Start Service
            organization: Ansible Product Demos (APD)
            job_args:
              extra_vars:
                _hosts: '{{ web_server_inventory_hostname }}'
                service_name: '{{ web_server_service_name | default("httpd") }}'

...
# vim: ft=yaml.ansible
