---
- name: Monitor SQS queue for EC2 RunInstances events
  hosts: all
  sources:
    - name: CloudTrail EC2 Events
      amazon.aws.aws_sqs_queue:
        name: '{{ sqs_queue_name | default("apd-cloudtrail-queue") }}'
        region: '{{ sqs_queue_region | default("us-east-2") }}'
        delay_seconds: 10

  rules:
    - name: Run fact scan on new EC2 instance
      condition: event.body.detail.eventName == "RunInstances"
      action:
        run_job_template:
          name: EDA | EC2 Instance Fact Scan
          organization: Ansible Product Demos (APD)
          job_args:
            extra_vars:
              instance_id: '{{ event.body.detail.responseElements.instancesSet["items"][0].instanceId }}'
              instance_name: '{{ event.body.detail.requestParameters.tagSpecificationSet["items"][0].tags[0].value }}'
              aws_region: '{{ event.body.detail.awsRegion }}'

...
# vim: ft=yaml.ansible
