---
- name: Install APD extras
  hosts: localhost
  gather_facts: false

  vars:
    apd_extras_git_repo: https://github.com/jce-redhat/apd-extras.git
    apd_extras_git_repo_branch: main
    session_cookie_age: 3600

  tasks:
    - name: Install APD extras
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        gateway_settings:
          SESSION_COOKIE_AGE: '{{ session_cookie_age }}'
        controller_projects:
          - name: APD Extras
            organization: Ansible Product Demos (APD)
            scm_type: git
            scm_url: '{{ apd_extras_git_repo }}'
            scm_branch: '{{ apd_extras_git_repo_branch }}'
            default_environment: Product Demos EE
            wait: true
        controller_templates:
          - name: APD Extras | Install extra demo
            job_type: run
            inventory: Ansible Product Demos Inventory
            credentials:
              - AAP Credential
            project: APD Extras
            playbook: playbooks/install-demo.yml
            survey_enabled: true
            survey:
              name: ''
              description: ''
              spec:
                - question_name: Name of extra demo
                  variable: demo
                  required: true
                  type: text
        eda_credentials:
          - name: AAP Credential for EDA
            description: Credential allowing rulebook activations to connect to the automation controller
            state: present
            credential_type: Red Hat Ansible Automation Platform
            organization: Ansible Product Demos (APD)
            inputs:
              # Note: API path required in AAP 2.5+ for AAP credential used by EDA
              host: '{{ lookup("env","AAP_HOSTNAME") | default("https://example.invalid") }}/api/controller'
              username: '{{ lookup("env","AAP_USERNAME") | default(omit) }}'
              password: '{{ lookup("env","AAP_PASSWORD") | default(omit) }}'
              oauth_token: '{{ lookup("env","AAP_TOKEN") | default(omit) }}'
              verify_ssl: '{{ lookup("env","AAP_VALIDATE_CERTS") | default(omit) }}'
        eda_projects:
          - name: APD Extras
            description: Additional AAP resources for use with Ansible Product Demos
            state: present
            scm_url: '{{ apd_extras_git_repo }}'
            scm_branch: '{{ apd_extras_git_repo_branch | default("main") }}'
            organization: Ansible Product Demos (APD)
            sync: true

...
# vim: ft=yaml.ansible
