---
- name: Install APD extra demo
  hosts: localhost
  gather_facts: false

  vars:
    # override with survey input
    demo: ''

  tasks:
    - name: Ensure demo name is set
      ansible.builtin.assert:
        that:
          - demo is not none and demo | length > 0
        fail_msg: The 'demo' variable must be set

    - name: Debug
      ansible.builtin.debug:
        var: playbook_dir

    - name: Determine project root directory from playbook_dir variable
      # noqa no-changed-when
      ansible.builtin.command:
        cmd: git rev-parse --show-toplevel
        chdir: '{{ playbook_dir }}'
      register: _repo_root

    # Rather than maintain a list of available demos in a survey, get a list
    # of available demo directories and ensure that the requested demo is in
    # the list
    - name: Get a list of demo directories
      ansible.builtin.find:
        paths: '{{ _repo_root.stdout }}/demos/'
        file_type: directory
        recurse: false
      register: _demo_dirs

    - name: Create list of available demos
      ansible.builtin.set_fact:
        available_demos: '{{ _demo_dirs.files | map(attribute="path") | map("basename") | list }}'

    - name: Ensure requested demo is available
      ansible.builtin.assert:
        that:
          - demo in available_demos
        fail_msg: The '{{ demo }}' demo is not available in this repository

    - name: Include "{{ demo }}" demo variables
      ansible.builtin.include_vars:
        file: '{{ _repo_root.stdout }}/demos/{{ demo }}/setup.yml'

    - name: Run aap_configuration dispatcher
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch

...
# vim: ft=yaml.ansible
